title: Iñigo's webpage
logo: /assets/img/portrait.jpg
description: I am Iñigo Muguruza Goenaga
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
mail: muguruzainigo@gmail.com
linkedin: https://www.linkedin.com/in/inigomuguruza
